### ISSUE TITLE
Can't import a couple of python modules using OSX

### ISSUE THREAD

**Issue by ssenaria** [tosher/Mediawiker#100]
I'm using sublime on my Mac, connecting to our Mediawiki page hosted with a hosting company. I'm seeing the following error message in the console. When I attempt to load the Python modules from the CLI, it works correctly.

```
ssen::Cloudberry
{~}-> python -c "import ordereddict"
ssen::Cloudberry
{~}->
```

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./mediawiker.py", line 24, in <module>
    from mwcommands import mw_utils as mw
  File "./mwcommands/__init__.py", line 4, in <module>
    from .mw_add_category import MediawikerAddCategoryCommand, MediawikerSetCategoryCommand
  File "./mwcommands/mw_add_category.py", line 13, in <module>
    import mw_utils as mw
  File "./mwcommands/mw_utils.py", line 16, in <module>
    from ordereddict import OrderedDict
ImportError: No module named ordereddict
```

**Comment by tosher** [comment]
Which version of Sublime Text you are using?

**Comment by ssenaria** [comment]
2.0.2

**Comment by tosher** [comment]
Thanks, i will check this moment..

**Comment by tosher** [comment]
Do you have installed the Package Control plugin?

**Comment by ssenaria** [comment]
I didn't use package control, I unzipped into the package folder.

**Comment by tosher** [comment]
Please, install this plugin. [Package control](https://packagecontrol.io/installation#st2) required for installation because it controls all dependencies of the plugins.. and ordereddict too.
Installation is easy and described on the page.
After installation of PC, it check all depends and will install them.
And installation of many other [plugins](https://packagecontrol.io/) will be more easy - in one-two clicks.

P.S. ST don't using python in your system, only embedded python version (2.6 for ST2 and 3.4 for ST3).
P.S.2 Sublime Text3 is better choice for this moment, many features available in ST3, but not in ST2.
